version: "3.3"

services:

  db:
    image: mysql:5.7
    container_name: mysql_db
    ports: 
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "library"
    networks:
      - rede_node

    # container_name: postgres
    # build:
    #   dockerfile: ./Dockerfile.postgresql
    #   context: .
    # tty: true
    # environment:
    #   POSTGRES_PASSWORD: 'password'
    #   POSTGRES_DB: 'projectdb'
    # ports:
    #   - '5432:5432'
    # expose:
    #   - '5432'
    # volumes:
    #   - ./docker/dbdata:/var/lib/postgresql/data
    # networks:
    #   - rede_node

  
  library_nest_api:
    container_name: node
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/app
    networks:
      - rede_node
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: postgres
      PMA_ARBITRARY: "1"
    ports:
      - "8080:80"
    networks:
      - rede_node

networks:
  rede_node:
    driver: bridge
