version: "3.3"

services:

  db:
    image: mysql:5.7
    container_name: mysql_db
    ports: 
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "library"
    networks:
      - rede_node

  
  library_nest_api:
    container_name: nest
    build: ./api
    ports:
      - "3000:3000"
    volumes:
      - ./api:/usr/app
    networks:
      - rede_node
    depends_on:
      - db

  library_nest_front:
    container_name: react
    build: ./front
    ports:
      - "8000:8000"
    volumes:
      - ./front:/usr/app
    networks:
      - rede_node
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: postgres
      PMA_ARBITRARY: "1"
    ports:
      - "8080:80"
    networks:
      - rede_node

networks:
  rede_node:
    driver: bridge
